- Package name : Numpy

- Numpy means numerical python

- It is siilar to math package

- It completely fcuses on Math operations

    -mean, median, mode, variance, covariance etc

    - Distance btw two points

    - Linear algebra

    - Matrix ooperations etc.

- When it comes storing a numbers

    - List and tuples

    - array : numpy

    - tensors : tensorflow or pytorch
 
  

**use case-1**

In [8]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[]
for i,j in zip(l1,l2):
    l.append(i+j)
l

[11, 22, 33, 44]

In [10]:
l=[i+j for i,j in zip(l1,l2)]
l

[11, 22, 33, 44]

In [12]:
import numpy as np
l1=[10,20,30,40]
arr1= np.array(l1)
arr1

array([10, 20, 30, 40])

In [14]:
type(l1),type(arr1)

(list, numpy.ndarray)

In [16]:
l2=[1,2,3,4]
arr2= np.array(l2)
arr2

array([1, 2, 3, 4])

In [18]:
type(l2),type(arr2)

(list, numpy.ndarray)

In [20]:
l1*l2 # error

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


**use case 2**

In [33]:
import time
start=time.time()
l1=list(range(1,100000000))
l2=list(range(1,100000000))
mul=[i*j for i,j in zip(l1,l2)]
end=time.time()
print("total time taken is:",(end-start))

total time taken is: 68.15916609764099


In [37]:
import time
import numpy as np
start=time.time()
arr1= np.arange(1,100000000)
arr2= np.arange(1,100000000)
mul=arr1*arr2
end=time.time()
print("total time taken is:",(end-start))

total time taken is: 0.4947242736816406
